CREATE OR REPLACE PROCEDURE dw_gold.dim_CUSTOMERS()
BEGIN
  -- Truncate the target table
  EXECUTE IMMEDIATE '''
    TRUNCATE TABLE `dwbq-445617`.dw_gold.DIM_CUSTOMERS
  ''';

  -- Insert data into the target table
  EXECUTE IMMEDIATE '''
    INSERT INTO `dwbq-445617`.dw_gold.DIM_CUSTOMERS (SK_CUSTOMER, CUSTOMER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX)
    SELECT ROW_NUMBER() OVER () AS SK_CUSTOMER, 
           CUSTOMER_ID, COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE, ADDRESS, CITY, REGION, POSTAL_CODE, COUNTRY, PHONE, FAX
    FROM `dwbq-445617`.dw_silver.customers
  ''';
END;

CALL dw_gold.dim_CUSTOMERS()
